export const GET_HOME_COUNT_SUCCESS = 'GET_HOME_COUNT_SUCCESS';
export const GET_IPR_HOME_KEY_BRAND_SUCCESS = 'GET_IPR_HOME_KEY_BRAND_SUCCESS';
export const GET_IPR_HOME_KEY_PLATFORM_SUCCESS = 'GET_IPR_HOME_KEY_PLATFORM_SUCCESS';
export const GET_IPR_HOME_KEY_CATEGORY_SUCCESS = 'GET_IPR_HOME_KEY_CATEGORY_SUCCESS';
export const GET_IPR_HOME_KEY_TROTS_SUCCESS = 'GET_IPR_HOME_KEY_TROTS_SUCCESS';
export const GET_IPR_HOME_KEY_AREA_SUCCESS = 'GET_IPR_HOME_KEY_AREA_SUCCESS';
export const GET_IPR_HOME_NETWORK_SUCCESS = 'GET_IPR_HOME_NETWORK_SUCCESS';
export const GET_HOME_SUIT_CASE_COUNT_SUCCESS = 'GET_HOME_SUIT_CASE_COUNT_SUCCESS'