export const GET_OFFLINE_CASE_DETAIL_SUCCESS = 'GET_OFFLINE_CASE_DETAIL_SUCCESS';
export const GET_OFFLINE_CASE_LOGS_SUCCESS = 'GET_OFFLINE_CASE_LOGS_SUCCESS';
export const GET_OFFLINE_CASE_REPORT_SUCCESS = 'GET_OFFLINE_CASE_REPORT_SUCCESS'
export const GET_OFFLINE_CASE_PROCESS_DETAIL_SUCCESS = 'GET_OFFLINE_CASE_PROCESS_DETAIL_SUCCESS';
export const UPDATE_OFFLINE_CASE_PROCESS_DETAIL_SUCCESS = 'UPDATE_OFFLINE_CASE_PROCESS_DETAIL_SUCCESS';

