export const GET_APPRAISAL_LIST_SUCCESS = 'GET_APPRAISAL_LIST_SUCCESS'
export const UPDATE_APPRAISAL_LIST_SUCCESS = 'UPDATE_APPRAISAL_LIST_SUCCESS'
export const UPDATE_APPRAISAL_LIST_ERROR = 'UPDATE_APPRAISAL_LIST_ERROR'