export const GET_THREAD_LIST_SUCCESS = 'GET_THREAD_LIST_SUCCESS';
export const UPDATE_THREAD_LIST_SUCCESS = 'UPDATE_THREAD_LIST_SUCCESS';
export const UPDATE_THREAD_LIST_ERROR = 'UPDATE_THREAD_LIST_ERROR';
export const UPDATE_THREAD_CLASSIFICATION_SUCCESS = 'UPDATE_THREAD_CLASSIFICATION_SUCCESS';
export const GET_THREAD_DETAILS = 'GET_THREAD_DETAILS'