export const GET_MONITOR_MONITORING_SUCCESS = 'GET_MONITOR_MONITORING_SUCCESS';
export const GET_MONITOR_MANUAL_SUCCESS = 'GET_MONITOR_MANUAL_SUCCESS';
export const GET_MONITOR_PICTURE_SUCCESS = 'GET_MONITOR_PICTURE_SUCCESS';