export const GET_MONITOR_LIST_SUCCESS = 'GET_MONITOR_LIST_SUCCESS';
export const UPDATE_MONITOR_STATUS_SUCCESS = 'UPDATE_MONITOR_STATUS_SUCCESS';
export const UPDATE_MONITOR_STATUS_ERROR = 'UPDATE_MONITOR_STATUS_ERROR';