export const GET_OFFLINE_REPORT_SUCCESS = 'GET_OFFLINE_REPORT_SUCCESS'
export const UPDATE_OFFLINE_REPORT_SUCCESS = 'UPDATE_OFFLINE_REPORT_SUCCESS'
export const UPDATE_OFFLINE_REPORT_ERROR = 'UPDATE_OFFLINE_REPORT_ERROR'
