export const GET_REPORT_APPLIVATION_SUCCESS = 'GET_REPORT_APPLIVATION_SUCCESS'
export const UPDATE_REPORT_APPLIVATION_SUCCESS = 'UPDATE_REPORT_APPLIVATION_SUCCESS'
export const UPDATE_REPORT_APPLIVATION_ERROR = 'UPDATE_REPORT_APPLIVATION_ERROR'

