export const GET_ONLINE_REPORT_SUCCESS = 'GET_ONLINE_REPORT_SUCCESS'
export const UPDATE_ONLINE_REPORT_SUCCESS = 'UPDATE_ONLINE_REPORT_SUCCESS'
export const UPDATE_ONLINE_REPORT_ERROR = 'UPDATE_ONLINE_REPORT_ERROR'
