export const GET_REPORT_TASK_SUCCESS = 'GET_REPORT_TASK_SUCCESS'
export const UPDATE_REPORT_TASK_SUCCESS = 'UPDATE_REPORT_TASK_SUCCESS'
export const UPDATE_REPORT_TASK_ERROR = 'UPDATE_REPORT_TASK_ERROR'