export const GET_REPORT_STATISTIC_SUCCESS = 'GET_REPORT_STATISTIC_SUCCESS'
export const GET_REPORT_BRANDINFO_SUCCESS = 'GET_REPORT_BRANDINFO_SUCCESS'
export const GET_REPORT_BRANDINFO_REEOR = 'GET_REPORT_BRANDINFO_REEOR'
export const GET_REPORT_COUNT_SUCCESS = 'GET_REPORT_COUNT_SUCCESS'
