export const GET_AUTHORITY_SUCCESS = 'GET_AUTHORITY_SUCCESS'
export const GET_AUTHORITY_ERROR = 'GET_AUTHORITY_ERROR'
export const UPDATE_AUTHORITY_SUCCESS = 'UPDATE_AUTHORITY_SUCCESS'
export const UPDATE_AUTHORITY_ERROR = 'UPDATE_AUTHORITY_ERROR'