export const GET_CATEGORY_LIST_SUCCESS = 'GET_CATEGORY_LIST_SUCCESS'
export const UPDATE_CATEGORY_LIST_SUCCESS = 'UPDATE_CATEGORY_LIST_SUCCESS'
export const UPDATE_CATEGORY_LIST_ERROR = 'UPDATE_CATEGORY_LIST_ERROR'