export const GET_DICTONARY_LIST_SUCCESS = 'GET_DICTONARY_LIST_SUCCES'
export const GET_DICTONARY_TYPE_DATA = 'GET_DICTONARY_TYPE_DATA'
export const UPDATE_DICTONARY_LIST_SUCCESS = 'UPDATE_DICTONARY_LIST_SUCCESS'
export const UPDATE_DICTONARY_LIST_ERROR = 'UPDATE_DICTONARY_LIST_ERROR'