export const GET_EXCEL_EXPORT_SUCCESS = 'GET_EXCEL_EXPORT_SUCCESS';
export const GET_EXCEL_EXPORT_ERROR = 'GET_EXCEL_EXPORT_ERROR';
export const UPDATE_EXCEL_EXPORT_SUCCESS = 'UPDATE_EXCEL_EXPORT_SUCCESS';
export const UPDATE_EXCEL_EXPORT_ERROR = 'UPDATE_EXCEL_EXPORT_ERROR';