export const GET_SCRIPT_LOG_LIST_SUCCESS = 'GET_SCRIPT_LOG_LIST_SUCCESS';
export const GET_SCRIPT_LOG_LIST_ERROR = 'GET_SCRIPT_LOG_LIST_ERROR';
export const UPDATE_SCRIPT_LOG_LIST_SUCCESS = 'UPDATE_SCRIPT_LOG_LIST_SUCCESS';
export const UPDATE_SCRIPT_LOG_LIST_ERROR = 'UPDATE_SCRIPT_LOG_LIST_ERROR';