export const GET_VERSION_LIST_SUCCESS = 'GET_VERSION_LIST_SUCCESS'
export const UPDATE_VERSION_LIST_SUCCESS = 'UPDATE_VERSION_LIST_SUCCESS'
export const UPDATE_VERSION_LIST_ERROR = 'UPDATE_VERSION_LIST_ERROR'