export const GET_WHITE_LIST_SUCCESS = 'GET_WHITE_LIST_SUCCESS'
export const GET_UPDATE_WHITE_LIST_SUCCESS = 'GET_UPDATE_WHITE_LIST_SUCCESS'
export const GET_ADD_WHITE_SUCCESS = 'GET_ADD_WHITE_SUCCESS'