export const GET_LAWYER_LIST_SUCCESS = 'GET_LAWYER_LIST_SUCCESS'
export const UPDATE_LAWYER_LIST_SUCCESS = 'UPDATE_LAWYER_LIST_SUCCESS'
export const UPDATE_LAWYER_LIST_ERROR = 'UPDATE_LAWYER_LIST_ERROR'
