export const GET_VOLUNTEER_LIST_SUCCESS = 'GET_VOLUNTEER_LIST_SUCCESS';
export const UPDATE_VOLUNTEER_STATUS_SUCCESS = 'UPDATE_VOLUNTEER_STATUS_SUCCESS';
export const UPDATE_VOLUNTEER_STATUS_ERROR = 'UPDATE_VOLUNTEER_STATUS_ERROR';