export const GET_CASE_DETAIL_SUCCESS = 'GET_CASE_DETAIL_SUCCESS';
export const GET_COMPANY_DETAIL_SUCCESS = 'GET_COMPANY_DETAIL_SUCCESS';
export const GET_PROCESS_DETAIL_SUCCESS = 'GET_PROCESS_DETAIL_SUCCESS';
export const GET_PROD_DETAIL_SUCCESS = 'GET_PROD_DETAIL_SUCCESS';
export const GET_SUIT_DETAIL_SUCCESS = 'GET_SUIT_DETAIL_SUCCESS';
export const GET_WARN_DETAIL_SUCCESS = 'GET_WARN_DETAIL_SUCCESS';
export const GET_BASIC_DETAIL_SUCCESS = 'GET_BASIC_DETAIL_SUCCESS';
export const UPDATE_CASE_DETAIL_SUCCESS = 'UPDATE_CASE_DETAIL_SUCCESS';
export const UPDATE_COMPANY_DETAIL_SUCCESS = 'UPDATE_COMPANY_DETAIL_SUCCESS';
export const UPDATE_PROCESS_DETAIL_SUCCESS = 'UPDATE_PROCESS_DETAIL_SUCCESS';
export const UPDATE_PROD_DETAIL_SUCCESS = 'UPDATE_PROD_DETAIL_SUCCESS';
export const UPDATE_SUIT_DETAIL_SUCCESS = 'UPDATE_SUIT_DETAIL_SUCCESS';
export const UPDATE_WARN_DETAIL_SUCCESS = 'UPDATE_WARN_DETAIL_SUCCESS';
export const GET_CASE_PROD_DETILS_LIST = 'GET_CASE_PROD_DETILS_LIST'

