export const GET_BRAND_LISTDATA_SUCCESS = 'GET_BRAND_LISTDATA_SUCCESS'
export const UPDATE_BRAND_LIST_EIDT_SUCCESS = 'UPDATE_BRAND_LIST_EIDT_SUCCESS'
export const UPDATE_BRAND_LIST_EDIT_ERROR = 'UPDATE_BRAND_LIST_EDIT_ERROR'
export const GET_BRAND_EDIT_DETAIL_SUCCESS = 'GET_BRAND_EDIT_DETAIL_SUCCESS'