
export const GET_BRAND_LIST_SUCCESS = 'GET_BRAND_LIST_SUCCESS';
export const GET_PROD_LIST_SUCCESS = 'GET_PROD_LIST_SUCCESS';
export const GET_PERMISSION_LIST_SUCCESS = 'GET_PERMISSION_LIST_SUCCESS';
export const GET_FILTERLIST_SUCCESS = 'GET_FILTERLIST_SUCCESS';
export const CHANGE_COLLAPSED_SUCCESS = 'CHANGE_COLLAPSED_SUCCESS';
export const CHANGE_LANGUAGE_SUCCESS = 'CHANGE_LANGUAGE_SUCCESS';
export const GET_CASE_AUDIT_STATUS_LIST = "GET_CASE_AUDIT_STATUS_LIST";
export const GET_OWNER_BRAND_LIST_SUCCESS = 'GET_OWNER_BRAND_LIST_SUCCESS';
export const GET_CHANNEL_LIST_SUCCESS = 'GET_CHANNEL_LIST_SUCCESS';
export const GET_TRADEMARK_LIST_SUCCESS = 'GET_TRADEMARK_LIST_SUCCESS';
export const GET_REPORT_REASON_LIST_SUCCESS = 'GET_REPORT_REASON_LIST_SUCCESS';
export const GET_SYSTEM_DICTONARY_SUCCESS = 'GET_SYSTEM_DICTONARY_SUCCESS';
export const GET_REPORT_REASON_QUERY_LIST_SUCCESS = 'GET_REPORT_REASON_QUERY_LIST_SUCCESS';
export const GET_TRADEMARK_QUERY_LIST_SUCCESS = 'GET_TRADEMARK_QUERY_LIST_SUCCESS';
export const GET_EXPORT_EXCEL_TITLE_SUCCESS = 'GET_EXPORT_EXCEL_TITLE_SUCCESS';
export const GET_LAWYER_BRAND_LIST_SUCCESS = 'GET_LAWYER_BRAND_LIST_SUCCESS'
export const GET_LAWYER_ROLE_TYPE_SUCCESS = 'GET_LAWYER_ROLE_TYPE_SUCCESS'